return {
  {
    "kylechui/nvim-surround",
    keys = {
      -- { "zs", mode = { "n", "v" }},
      -- { "ds", mode = { "n", "v" }},
      -- { "cs", mode = { "n", "v" }},
      -- { "<leader>~", mode = { "n", "v" }},
      -- { "<leader>*", mode = { "n", "v" }},
      -- { "<leader>$", mode = { "n", "v" }},
      -- { "<leader>`", mode = { "n", "v" }},
      -- { "<leader>>", mode = { "n", "v" }},
      -- { "<leader><", mode = { "n", "v" }},
      -- { "<leader>'", mode = { "n", "v" }},
      -- { "<leader>\"", mode = { "n", "v" }},
      -- { "<leader>}", mode = { "n", "v" }},
      -- { "<leader>{", mode = { "n", "v" }},
      -- { "<leader>]", mode = { "n", "v" }},
      -- { "<leader>[", mode = { "n", "v" }},
      -- { "<leader>)", mode = { "n", "v" }},
      { mode="n", "<leader>(", "<Plug>(nvim-surround-normal)iw(" },
      { mode="n", "<leader>)", "<Plug>(nvim-surround-normal)iw)" },
      { mode="n", "<leader>[", "<Plug>(nvim-surround-normal)iw[" },
      { mode="n", "<leader>]", "<Plug>(nvim-surround-normal)iw]" },
      { mode="n", "<leader>{", "<Plug>(nvim-surround-normal)iw{" },
      { mode="n", "<leader>}", "<Plug>(nvim-surround-normal)iw}" },
      { mode="n", "<leader>\"", "<Plug>(nvim-surround-normal)iw\"" },
      { mode="n", "<leader>'", "<Plug>(nvim-surround-normal)iw'" },
      { mode="n", "<leader><", "<Plug>(nvim-surround-normal)iw<" },
      { mode="n", "<leader>>", "<Plug>(nvim-surround-normal)iw>" },
      { mode="n", "<leader>`", "<Plug>(nvim-surround-normal)iw`" },
      { mode="n", "<leader>$", "<Plug>(nvim-surround-normal)iw$" },
      { mode="n", "<leader>*", "<Plug>(nvim-surround-normal)iw*" },
      { mode="n", "<leader>~", "<Plug>(nvim-surround-normal)iw~" },

      { mode="v", "<leader>(", "<Plug>(nvim-surround-visual)(" },
      { mode="v", "<leader>)", "<Plug>(nvim-surround-visual))" },
      { mode="v", "<leader>[", "<Plug>(nvim-surround-visual)[" },
      { mode="v", "<leader>]", "<Plug>(nvim-surround-visual)]" },
      { mode="v", "<leader>{", "<Plug>(nvim-surround-visual){" },
      { mode="v", "<leader>}", "<Plug>(nvim-surround-visual)}" },
      { mode="v", "<leader>\"", "<Plug>(nvim-surround-visual)\"" },
      { mode="v", "<leader>'", "<Plug>(nvim-surround-visual)'" },
      { mode="v", "<leader><", "<Plug>(nvim-surround-visual)<" },
      { mode="v", "<leader>>", "<Plug>(nvim-surround-visual)>" },
      { mode="v", "<leader>`", "<Plug>(nvim-surround-visual)`" },
      { mode="v", "<leader>$", "<Plug>(nvim-surround-visual)$" },
      { mode="v", "<leader>*", "<Plug>(nvim-surround-visual)*" },
      { mode="v", "<leader>~", "<Plug>(nvim-surround-visual)~" },
    },
    config = function ()
      vim.cmd([[highlight default link NvimSurroundHighlight DiffChange]])
      require("nvim-surround").setup({
        keymaps = {
          insert = "<C-g>s",
          insert_line = "<C-g>S",
          normal = "zs",
          normal_cur = "zsw",
          normal_line = "zsl",
          normal_cur_line = "zsS",
          visual = "zs",
          visual_line = "zsl",
          delete = "ds",
          change = "cs",
        },
      })
    end
  }
}
